### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [shawnlinxl/freshr#1]
I see

```
Error in teardown_env() : `teardown_env()` has not been initialized
ℹ This is an internal error that was detected in the testthat package.
  Please report it at <https://github.com/r-lib/testthat/issues> with a reprex and the full backtrace.
```

I don't think it's possible to test your package using testthat since it testthat is not designed to be work if it's forcibly `detach`ed during testing.

**Comment by hadley** [comment]
Just to let you know, we're planning on submitting testthat to CRAN on Oct 7.

**Comment by shawnlinxl** [comment]
> Just to let you know, we're planning on submitting testthat to CRAN on Oct 7.

**Comment by hadley** [comment]
It's up to you. If you don't resubmit to CRAN they'll send you an email...

**Comment by shawnlinxl** [comment]
925a4a7de39ee646dd83cda51c55a75a846b343f

**Comment by shawnlinxl** [comment]
> It's up to you. If you don't resubmit to CRAN they'll send you an email...

Thank you, Hadley. I've updated the package and resubmitted to CRAN.
